### ISSUE TITLE
EXC_BAD_ACCESS VKVotable.m:34

### ISSUE THREAD

**Issue by squishykid** [AmarJayR/VoatKit#8]
Maybe something to do with either the upvotes or downvotes field being deallocated. Changing the property from "assign" to "copy" seems to fix the issue. (VKVotable.h:22&27)

**Comment by AmarJayR** [comment]
You're right, those should both be "copy". Strange that I'm not getting this error though. Can you provide some more info on the architecture you're building for & the code you're using?
